name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup rust
      run: rustup target add wasm32-wasi
    - name: Build plugin
      run: cd plugin-system && cargo build --release --target wasm32-wasi && mv target/wasm32-wasi/release/sample_plugin.wasm ../plugin.wasm
    - name: Run app
      run: cargo run
